all: FindDevices NewAddress

FindDevices             :FindDevices.cpp ../iarduino_I2C_Joystick.cpp
NewAddress              :NewAddress.cpp ../iarduino_I2C_Joystick.cpp

clean:
	rm -f FindDevices NewAddress
